

# This file was *autogenerated* from the file matrix.sage
from sage.all_cmdline import *   # import sage library

_sage_const_52435875175126190479447740508185965837690552500527637822603658699938581184513 = Integer(52435875175126190479447740508185965837690552500527637822603658699938581184513); _sage_const_256 = Integer(256)# scalar field of the curve = Fr
field_modulus = _sage_const_52435875175126190479447740508185965837690552500527637822603658699938581184513 
F = GF(field_modulus)

load('/Users/marcin/personal/zkhack-bls-pedersen/M256.sage')
my_msg_hash = load('/Users/marcin/personal/zkhack-bls-pedersen/my_msg_hash.sage')

ms_vec_f = list(map(lambda x: F(x), ms_vec_binary)
M = matrix(_sage_const_256 , _sage_const_256 , ms_vec_f)

inv = M.inverse()

B = list(map(lambda x: F(x), my_msg_hash)

x = inv * B

